version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql_proyecto
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./MySQL:/var/lib/mysql
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_USER=mendez
          - MYSQL_PASSWORD=citawebdb
        ports:
          - "3307:3306"
        expose: 
          - "3307"
  apache-php:
    image: php:8.1-apache
    container_name: php_proyecto
    build:
      context: ./
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8001:80"
    depends_on:
      - mysql
    expose:
      - "8001"